áreas de login e cadastro
diogogomes3/crud-produtos-sabion pull request #1
Opened 2020-10-27 15:49 UTC by diogogomes3

2020-10-27 15:58 UTC, Bruno-Sampaio requested changes

2020-10-27 15:58 UTC, Bruno-Sampaio commented on src/pages/cadastro.html
> +        <form id="register-form">
Faltou fechar a tag form

2020-10-27 15:58 UTC, Bruno-Sampaio commented on src/pages/cadastro.html
> +            <li class="sign-up"><a href="login.html">Cadastrar</a></li>
cadastrar deveria ser um botão

2020-10-27 16:24 UTC, ezequiel-7 requested changes

2020-10-27 16:24 UTC, ezequiel-7 commented on src/pages/login.html
> +        <form id="register-form">
Falta o fechamento da tag form

2020-10-27 16:24 UTC, ezequiel-7 commented on src/pages/login.html
> +            <li class="enter"><a href="../index.html">Entrar</a></li>
`<button>` deveria estar no lugar do `<li>` e depois fazer a navegação no submit.

2020-10-27 16:24 UTC, ezequiel-7 commented on src/styles/login.css
> +#main-container2{
No lugar do numero 2, poderia ser "main-container-cadastro"

2020-10-27 16:24 UTC, ezequiel-7 commented on src/styles/login.css
> +input[type="submit"]{
Pode tirar esse `input[type="sumit"]`, porque não está sendo utilizado no  html.

2020-10-30 13:35 UTC, monica-santos requested changes

2020-10-30 13:35 UTC, monica-santos commented on src/pages/login.html
> +        <div class="full-box">
essa div está sem a tag de fechamento

2020-10-30 13:35 UTC, monica-santos commented on src/pages/login.html
> +        </div>
esse fechamento de div é o da `<div class="full-box">` mas está depois do fechamento do form, deveria estar antes

2020-10-30 13:52 UTC, iuriian requested changes

2020-10-30 13:52 UTC, iuriian commented on src/pages/cadastro.html
> +            <label for="text">Nome</label>
Corrigir o valor do atributo `for` do elemento `label` para que contenha o valor do atributo `name` do input ao qual pertence.

2020-10-30 13:52 UTC, iuriian commented on src/pages/cadastro.html
> +            <label for="text">Sobrenome</label>
Corrigir o valor do atributo `for` do elemento `label` para que contenha o valor do atributo `name` do input ao qual pertence.

2020-10-30 13:52 UTC, iuriian commented on src/pages/cadastro.html
> +            <label for="password">Senha</label>
Corrigir o valor do atributo `for` do elemento `label` para que contenha o valor do atributo `name` do input ao qual pertence.

2020-10-30 13:52 UTC, iuriian commented on src/pages/cadastro.html
> +            <label for="password">Confirme sua senha</label>
Corrigir o valor do atributo `for` do elemento `label` para que contenha o valor do atributo `name` do input ao qual pertence.

2020-10-30 13:52 UTC, iuriian commented on src/pages/cadastro.html
> +            <input type="password" name="password" id="password" placeholder="Digite a senha novamente" />
Alterar o valor do atributo `name` do input, pois existem 2 elementos com o mesmo valor e isso pode gerar problemas, assim como o `id` também estão iguais

2020-10-30 13:52 UTC, iuriian commented on src/styles/login.css
> +input:focus, label:focus{
Evitar o uso de elemento para estilizar, sempre prefira a utilização de classes ou ids(caso seja algo muito específico)

2020-10-30 13:52 UTC, iuriian commented on src/styles/login.css
> +body{
Resets devem ser as primeiras definições da folha de estilo.

2020-10-30 13:52 UTC, iuriian commented on src/styles/login.css
> +*{
Resets devem ser as primeiras definições da folha de estilo.

2020-10-30 13:52 UTC, iuriian commented on src/styles/login.css
> +input, label{
Evitar o uso de elemento para estilizar, sempre prefira a utilização de classes ou ids(caso seja algo muito específico)

2020-10-30 13:52 UTC, iuriian commented on src/styles/login.css
> +form{
Evitar o uso de elemento para estilizar, sempre prefira a utilização de classes ou ids(caso seja algo muito específico)

2020-10-30 13:52 UTC, iuriian commented on src/styles/login.css
> +label{
Além da utilização do elemento para estilização, existe redundância, pois este estilo poderia ter sido resolvido acima, onde é utilizado o mesmo elemento

2020-10-30 13:52 UTC, iuriian commented on src/styles/login.css
> +input{
Além da utilização do elemento para estilização, existe redundância, pois este estilo poderia ter sido resolvido acima, onde é utilizado o mesmo elemento

2020-11-11 14:57 UTC, Bruno-Sampaio approved these changes
Muito bom 👍

2020-11-11 15:16 UTC, merged