Feature/lista produtos
diogogomes3/crud-produtos-sabion pull request #2
Opened 2020-10-27 16:29 UTC by Bruno-Sampaio

Lista de produtos !

2020-10-28 12:36 UTC, iuriian requested changes

2020-10-28 12:36 UTC, iuriian commented on src/pages/listaprodutos.html
> +      <div class="Pe">
De acordo com a boas práticas de css, todas as classes devem ser escritas em letras minúsculas

2020-10-28 12:36 UTC, iuriian commented on src/styles/listaprodutos.css
> +footer{
Evitar estilização através de elementos, utilize classes e ids

2020-10-28 12:36 UTC, iuriian commented on src/styles/listaprodutos.css
> +    background-color:  rgba(255, 255, 255, 0.842);
Sempre que possível utilize cores no formato hexadecimal(#00000)

2020-10-28 12:36 UTC, iuriian commented on src/styles/listaprodutos.css
> +ul li a{
Evitar estilização através de elementos, utilize classes e ids

2020-10-28 12:36 UTC, iuriian commented on src/pages/listaprodutos.html
> +           <p class="codigo">00000</p>
Esta classe não foi criada na folha de estilo(css)

2020-10-28 12:36 UTC, iuriian commented on src/pages/listaprodutos.html
> +           <p class="descricao">descrição aaaaaaaaaaaaaaa.</p>
Esta classe não foi criada na folha de estilo(css)

2020-10-28 12:36 UTC, iuriian commented on src/pages/listaprodutos.html
> +           <p class="totaldeprodutos">total de produtos 10milhões.</p>
Esta classe não foi criada na folha de estilo(css)

2020-10-28 14:17 UTC, diogogomes3 reviewed
Nâo vi nenhum outro erro ou observação a ser apontada a não ser as doo Iuri.

2020-10-30 14:01 UTC, iuriian requested changes

2020-10-30 14:01 UTC, iuriian commented on src/pages/listaprodutos.html
> +
Retirar espaçamentos

2020-10-30 14:01 UTC, iuriian commented on src/pages/listaprodutos.html
> +         <ul class="ueli">
O nome desta classe não está claro

2020-10-30 14:01 UTC, iuriian commented on src/pages/listaprodutos.html
> +           <li class="elii"><a class="content" href="#">Faça seu login aqui</a></li>
O nome desta classe não está claro

2020-11-11 15:16 UTC, merged