cadastro de produto
diogogomes3/crud-produtos-sabion pull request #3
Opened 2020-10-27 16:46 UTC by ezequiel-7

Primeiro pull no cadastro de produtos.

2020-10-28 13:58 UTC, diogogomes3 requested changes

2020-10-28 13:58 UTC, diogogomes3 commented on src/pages/cadastroproduto.html
> +                <input type="email" name="email" id="email" placeholder="Digite se e-mail">
Trocar "Digite se e-mail" por "Digite seu e-mail".

2020-10-28 13:58 UTC, diogogomes3 commented on src/pages/cadastroproduto.html
> +                <input  type="submit" id="btn-submit" value="Registrar">
Ao invés de usar o `<input type="submit">`, usar a tag `<button>`

2020-10-30 13:43 UTC, monica-santos requested changes

2020-10-30 13:43 UTC, monica-santos commented on src/pages/cadastroproduto.html
> +            <div class="full-box">
imagino que para o cadastro de produto, não seja necessário aceitar algum termo de uso, pode retirar essa parte

2020-10-30 13:43 UTC, monica-santos commented on src/pages/cadastroproduto.html
> +            <div class="half-box">
todos os inputs estão com o `name` e `id` iguais, pode alterar para que cada um tenha o nome relativo ao que realmente é. por exemplo, esse seria **codigo**.
E tem que alterar o `for` do label `também`

2020-10-30 14:08 UTC, iuriian requested changes

2020-10-30 14:08 UTC, iuriian commented on src/styles/cadastroproduto.css
> +body{
Resets por padrão ficam nas primeiras linhas da folha de estilo

2020-10-30 14:08 UTC, iuriian commented on src/styles/cadastroproduto.css
> +input, label{
Evitar o uso de elementos para estilização

2020-10-30 14:08 UTC, iuriian commented on src/styles/cadastroproduto.css
> +input:focus, label:focus{
Evitar o uso de elementos para estilização

2020-10-30 14:08 UTC, iuriian commented on src/styles/cadastroproduto.css
> +a{
Evitar o uso de elementos para estilização

2020-10-30 14:08 UTC, iuriian commented on src/styles/cadastroproduto.css
> +form{
Evitar o uso de elementos para estilização

2020-10-30 14:08 UTC, iuriian commented on src/styles/cadastroproduto.css
> +label{
Evitar o uso de elementos para estilização

2020-10-30 14:08 UTC, iuriian commented on src/styles/cadastroproduto.css
> +input{
Evitar o uso de elementos para estilização

2020-10-30 14:08 UTC, iuriian commented on src/styles/cadastroproduto.css
> +input:focus{
Evitar o uso de elementos para estilização

2020-11-11 14:31 UTC, diogogomes3 submitted a review, later dismissed

2020-11-11 15:19 UTC, diogogomes3 approved these changes

2020-11-11 15:23 UTC, merged